// Code generated by protoc-gen-gogo.
// source: gogo.proto
// DO NOT EDIT!

/*
Package gogoproto is a generated protocol buffer package.

It is generated from these files:
	gogo.proto

It has these top-level messages:
*/
package gogoproto

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

var E_GoprotoEnumPrefix = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62001,
	Name:          "gogoproto.goproto_enum_prefix",
	Tag:           "varint,62001,opt,name=goproto_enum_prefix,json=goprotoEnumPrefix",
}

var E_GoprotoEnumStringer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62021,
	Name:          "gogoproto.goproto_enum_stringer",
	Tag:           "varint,62021,opt,name=goproto_enum_stringer,json=goprotoEnumStringer",
}

var E_EnumStringer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62022,
	Name:          "gogoproto.enum_stringer",
	Tag:           "varint,62022,opt,name=enum_stringer,json=enumStringer",
}

var E_EnumCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         62023,
	Name:          "gogoproto.enum_customname",
	Tag:           "bytes,62023,opt,name=enum_customname,json=enumCustomname",
}

var E_EnumvalueCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         66001,
	Name:          "gogoproto.enumvalue_customname",
	Tag:           "bytes,66001,opt,name=enumvalue_customname,json=enumvalueCustomname",
}

var E_GoprotoGettersAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63001,
	Name:          "gogoproto.goproto_getters_all",
	Tag:           "varint,63001,opt,name=goproto_getters_all,json=goprotoGettersAll",
}

var E_GoprotoEnumPrefixAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63002,
	Name:          "gogoproto.goproto_enum_prefix_all",
	Tag:           "varint,63002,opt,name=goproto_enum_prefix_all,json=goprotoEnumPrefixAll",
}

var E_GoprotoStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63003,
	Name:          "gogoproto.goproto_stringer_all",
	Tag:           "varint,63003,opt,name=goproto_stringer_all,json=goprotoStringerAll",
}

var E_VerboseEqualAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63004,
	Name:          "gogoproto.verbose_equal_all",
	Tag:           "varint,63004,opt,name=verbose_equal_all,json=verboseEqualAll",
}

var E_FaceAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63005,
	Name:          "gogoproto.face_all",
	Tag:           "varint,63005,opt,name=face_all,json=faceAll",
}

var E_GostringAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63006,
	Name:          "gogoproto.gostring_all",
	Tag:           "varint,63006,opt,name=gostring_all,json=gostringAll",
}

var E_PopulateAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63007,
	Name:          "gogoproto.populate_all",
	Tag:           "varint,63007,opt,name=populate_all,json=populateAll",
}

var E_StringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63008,
	Name:          "gogoproto.stringer_all",
	Tag:           "varint,63008,opt,name=stringer_all,json=stringerAll",
}

var E_OnlyoneAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63009,
	Name:          "gogoproto.onlyone_all",
	Tag:           "varint,63009,opt,name=onlyone_all,json=onlyoneAll",
}

var E_EqualAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63013,
	Name:          "gogoproto.equal_all",
	Tag:           "varint,63013,opt,name=equal_all,json=equalAll",
}

var E_DescriptionAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63014,
	Name:          "gogoproto.description_all",
	Tag:           "varint,63014,opt,name=description_all,json=descriptionAll",
}

var E_TestgenAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63015,
	Name:          "gogoproto.testgen_all",
	Tag:           "varint,63015,opt,name=testgen_all,json=testgenAll",
}

var E_BenchgenAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63016,
	Name:          "gogoproto.benchgen_all",
	Tag:           "varint,63016,opt,name=benchgen_all,json=benchgenAll",
}

var E_MarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63017,
	Name:          "gogoproto.marshaler_all",
	Tag:           "varint,63017,opt,name=marshaler_all,json=marshalerAll",
}

var E_UnmarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63018,
	Name:          "gogoproto.unmarshaler_all",
	Tag:           "varint,63018,opt,name=unmarshaler_all,json=unmarshalerAll",
}

var E_StableMarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63019,
	Name:          "gogoproto.stable_marshaler_all",
	Tag:           "varint,63019,opt,name=stable_marshaler_all,json=stableMarshalerAll",
}

var E_SizerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63020,
	Name:          "gogoproto.sizer_all",
	Tag:           "varint,63020,opt,name=sizer_all,json=sizerAll",
}

var E_GoprotoEnumStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63021,
	Name:          "gogoproto.goproto_enum_stringer_all",
	Tag:           "varint,63021,opt,name=goproto_enum_stringer_all,json=goprotoEnumStringerAll",
}

var E_EnumStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63022,
	Name:          "gogoproto.enum_stringer_all",
	Tag:           "varint,63022,opt,name=enum_stringer_all,json=enumStringerAll",
}

var E_UnsafeMarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63023,
	Name:          "gogoproto.unsafe_marshaler_all",
	Tag:           "varint,63023,opt,name=unsafe_marshaler_all,json=unsafeMarshalerAll",
}

var E_UnsafeUnmarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63024,
	Name:          "gogoproto.unsafe_unmarshaler_all",
	Tag:           "varint,63024,opt,name=unsafe_unmarshaler_all,json=unsafeUnmarshalerAll",
}

var E_GoprotoExtensionsMapAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63025,
	Name:          "gogoproto.goproto_extensions_map_all",
	Tag:           "varint,63025,opt,name=goproto_extensions_map_all,json=goprotoExtensionsMapAll",
}

var E_GoprotoUnrecognizedAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63026,
	Name:          "gogoproto.goproto_unrecognized_all",
	Tag:           "varint,63026,opt,name=goproto_unrecognized_all,json=goprotoUnrecognizedAll",
}

var E_GogoprotoImport = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63027,
	Name:          "gogoproto.gogoproto_import",
	Tag:           "varint,63027,opt,name=gogoproto_import,json=gogoprotoImport",
}

var E_ProtosizerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63028,
	Name:          "gogoproto.protosizer_all",
	Tag:           "varint,63028,opt,name=protosizer_all,json=protosizerAll",
}

var E_CompareAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63029,
	Name:          "gogoproto.compare_all",
	Tag:           "varint,63029,opt,name=compare_all,json=compareAll",
}

var E_DirectOneofAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63030,
	Name:          "gogoproto.direct_oneof_all",
	Tag:           "varint,63030,opt,name=direct_oneof_all,json=directOneofAll",
}

var E_GoprotoGetters = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64001,
	Name:          "gogoproto.goproto_getters",
	Tag:           "varint,64001,opt,name=goproto_getters,json=goprotoGetters",
}

var E_GoprotoStringer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64003,
	Name:          "gogoproto.goproto_stringer",
	Tag:           "varint,64003,opt,name=goproto_stringer,json=goprotoStringer",
}

var E_VerboseEqual = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64004,
	Name:          "gogoproto.verbose_equal",
	Tag:           "varint,64004,opt,name=verbose_equal,json=verboseEqual",
}

var E_Face = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64005,
	Name:          "gogoproto.face",
	Tag:           "varint,64005,opt,name=face",
}

var E_Gostring = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64006,
	Name:          "gogoproto.gostring",
	Tag:           "varint,64006,opt,name=gostring",
}

var E_Populate = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64007,
	Name:          "gogoproto.populate",
	Tag:           "varint,64007,opt,name=populate",
}

var E_Stringer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         67008,
	Name:          "gogoproto.stringer",
	Tag:           "varint,67008,opt,name=stringer",
}

var E_Onlyone = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64009,
	Name:          "gogoproto.onlyone",
	Tag:           "varint,64009,opt,name=onlyone",
}

var E_Equal = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64013,
	Name:          "gogoproto.equal",
	Tag:           "varint,64013,opt,name=equal",
}

var E_Description = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64014,
	Name:          "gogoproto.description",
	Tag:           "varint,64014,opt,name=description",
}

var E_Testgen = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64015,
	Name:          "gogoproto.testgen",
	Tag:           "varint,64015,opt,name=testgen",
}

var E_Benchgen = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64016,
	Name:          "gogoproto.benchgen",
	Tag:           "varint,64016,opt,name=benchgen",
}

var E_Marshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64017,
	Name:          "gogoproto.marshaler",
	Tag:           "varint,64017,opt,name=marshaler",
}

var E_Unmarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64018,
	Name:          "gogoproto.unmarshaler",
	Tag:           "varint,64018,opt,name=unmarshaler",
}

var E_StableMarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64019,
	Name:          "gogoproto.stable_marshaler",
	Tag:           "varint,64019,opt,name=stable_marshaler,json=stableMarshaler",
}

var E_Sizer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64020,
	Name:          "gogoproto.sizer",
	Tag:           "varint,64020,opt,name=sizer",
}

var E_UnsafeMarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64023,
	Name:          "gogoproto.unsafe_marshaler",
	Tag:           "varint,64023,opt,name=unsafe_marshaler,json=unsafeMarshaler",
}

var E_UnsafeUnmarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64024,
	Name:          "gogoproto.unsafe_unmarshaler",
	Tag:           "varint,64024,opt,name=unsafe_unmarshaler,json=unsafeUnmarshaler",
}

var E_GoprotoExtensionsMap = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64025,
	Name:          "gogoproto.goproto_extensions_map",
	Tag:           "varint,64025,opt,name=goproto_extensions_map,json=goprotoExtensionsMap",
}

var E_GoprotoUnrecognized = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64026,
	Name:          "gogoproto.goproto_unrecognized",
	Tag:           "varint,64026,opt,name=goproto_unrecognized,json=goprotoUnrecognized",
}

var E_Protosizer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64028,
	Name:          "gogoproto.protosizer",
	Tag:           "varint,64028,opt,name=protosizer",
}

var E_Compare = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64029,
	Name:          "gogoproto.compare",
	Tag:           "varint,64029,opt,name=compare",
}

var E_DirectOneof = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64030,
	Name:          "gogoproto.direct_oneof",
	Tag:           "varint,64030,opt,name=direct_oneof,json=directOneof",
}

var E_Nullable = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65001,
	Name:          "gogoproto.nullable",
	Tag:           "varint,65001,opt,name=nullable",
}

var E_Embed = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65002,
	Name:          "gogoproto.embed",
	Tag:           "varint,65002,opt,name=embed",
}

var E_Customtype = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65003,
	Name:          "gogoproto.customtype",
	Tag:           "bytes,65003,opt,name=customtype",
}

var E_Customname = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65004,
	Name:          "gogoproto.customname",
	Tag:           "bytes,65004,opt,name=customname",
}

var E_Jsontag = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65005,
	Name:          "gogoproto.jsontag",
	Tag:           "bytes,65005,opt,name=jsontag",
}

var E_Moretags = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65006,
	Name:          "gogoproto.moretags",
	Tag:           "bytes,65006,opt,name=moretags",
}

var E_Casttype = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65007,
	Name:          "gogoproto.casttype",
	Tag:           "bytes,65007,opt,name=casttype",
}

var E_Castkey = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65008,
	Name:          "gogoproto.castkey",
	Tag:           "bytes,65008,opt,name=castkey",
}

var E_Castvalue = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65009,
	Name:          "gogoproto.castvalue",
	Tag:           "bytes,65009,opt,name=castvalue",
}

func init() {
	proto.RegisterExtension(E_GoprotoEnumPrefix)
	proto.RegisterExtension(E_GoprotoEnumStringer)
	proto.RegisterExtension(E_EnumStringer)
	proto.RegisterExtension(E_EnumCustomname)
	proto.RegisterExtension(E_EnumvalueCustomname)
	proto.RegisterExtension(E_GoprotoGettersAll)
	proto.RegisterExtension(E_GoprotoEnumPrefixAll)
	proto.RegisterExtension(E_GoprotoStringerAll)
	proto.RegisterExtension(E_VerboseEqualAll)
	proto.RegisterExtension(E_FaceAll)
	proto.RegisterExtension(E_GostringAll)
	proto.RegisterExtension(E_PopulateAll)
	proto.RegisterExtension(E_StringerAll)
	proto.RegisterExtension(E_OnlyoneAll)
	proto.RegisterExtension(E_EqualAll)
	proto.RegisterExtension(E_DescriptionAll)
	proto.RegisterExtension(E_TestgenAll)
	proto.RegisterExtension(E_BenchgenAll)
	proto.RegisterExtension(E_MarshalerAll)
	proto.RegisterExtension(E_UnmarshalerAll)
	proto.RegisterExtension(E_StableMarshalerAll)
	proto.RegisterExtension(E_SizerAll)
	proto.RegisterExtension(E_GoprotoEnumStringerAll)
	proto.RegisterExtension(E_EnumStringerAll)
	proto.RegisterExtension(E_UnsafeMarshalerAll)
	proto.RegisterExtension(E_UnsafeUnmarshalerAll)
	proto.RegisterExtension(E_GoprotoExtensionsMapAll)
	proto.RegisterExtension(E_GoprotoUnrecognizedAll)
	proto.RegisterExtension(E_GogoprotoImport)
	proto.RegisterExtension(E_ProtosizerAll)
	proto.RegisterExtension(E_CompareAll)
	proto.RegisterExtension(E_DirectOneofAll)
	proto.RegisterExtension(E_GoprotoGetters)
	proto.RegisterExtension(E_GoprotoStringer)
	proto.RegisterExtension(E_VerboseEqual)
	proto.RegisterExtension(E_Face)
	proto.RegisterExtension(E_Gostring)
	proto.RegisterExtension(E_Populate)
	proto.RegisterExtension(E_Stringer)
	proto.RegisterExtension(E_Onlyone)
	proto.RegisterExtension(E_Equal)
	proto.RegisterExtension(E_Description)
	proto.RegisterExtension(E_Testgen)
	proto.RegisterExtension(E_Benchgen)
	proto.RegisterExtension(E_Marshaler)
	proto.RegisterExtension(E_Unmarshaler)
	proto.RegisterExtension(E_StableMarshaler)
	proto.RegisterExtension(E_Sizer)
	proto.RegisterExtension(E_UnsafeMarshaler)
	proto.RegisterExtension(E_UnsafeUnmarshaler)
	proto.RegisterExtension(E_GoprotoExtensionsMap)
	proto.RegisterExtension(E_GoprotoUnrecognized)
	proto.RegisterExtension(E_Protosizer)
	proto.RegisterExtension(E_Compare)
	proto.RegisterExtension(E_DirectOneof)
	proto.RegisterExtension(E_Nullable)
	proto.RegisterExtension(E_Embed)
	proto.RegisterExtension(E_Customtype)
	proto.RegisterExtension(E_Customname)
	proto.RegisterExtension(E_Jsontag)
	proto.RegisterExtension(E_Moretags)
	proto.RegisterExtension(E_Casttype)
	proto.RegisterExtension(E_Castkey)
	proto.RegisterExtension(E_Castvalue)
}

func init() { proto.RegisterFile("gogo.proto", fileDescriptorGogo) }

var fileDescriptorGogo = []byte{
	// 1133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x97, 0xcb, 0x6f, 0x1b, 0x55,
	0x14, 0x87, 0x85, 0x48, 0x15, 0xfb, 0xc4, 0x49, 0x1a, 0x27, 0x84, 0x52, 0x81, 0x68, 0x77, 0xac,
	0xd2, 0x15, 0x42, 0x9d, 0x0a, 0xa1, 0xb6, 0xa4, 0xa1, 0x88, 0xd0, 0x28, 0x90, 0x02, 0x62, 0x61,
	0x8d, 0x9d, 0xeb, 0xa9, 0x61, 0x3c, 0x77, 0x98, 0x3b, 0x53, 0x35, 0xec, 0x50, 0x79, 0x08, 0x21,
	0xde, 0x48, 0xd0, 0xd2, 0x16, 0x58, 0xf0, 0x7e, 0x96, 0xd7, 0x9a, 0x0d, 0xb0, 0xe6, 0x7f, 0x60,
	0x03, 0x94, 0x97, 0x94, 0x5d, 0x36, 0xbd, 0x67, 0xe6, 0x9c, 0xf1, 0x1d, 0xc7, 0xd2, 0xbd, 0xde,
	0x4d, 0xe2, 0xfb, 0x7d, 0xbe, 0x73, 0xce, 0xdc, 0xf3, 0xf3, 0x00, 0x04, 0x32, 0x90, 0x4b, 0x71,
	0x22, 0x53, 0xd9, 0xac, 0xe3, 0x75, 0x7e, 0xb9, 0xff, 0x40, 0x20, 0x65, 0x10, 0x8a, 0x43, 0xf9,
	0x5f, 0xed, 0xac, 0x7b, 0x68, 0x53, 0xa8, 0x4e, 0xd2, 0x8b, 0x53, 0x99, 0x14, 0x8b, 0xbd, 0x07,
	0x61, 0x9e, 0x16, 0xb7, 0x44, 0x94, 0xf5, 0x5b, 0x71, 0x22, 0xba, 0xbd, 0x73, 0xcd, 0x5b, 0x97,
	0x0a, 0x72, 0x89, 0xc9, 0xa5, 0x65, 0xfd, 0xe9, 0xa9, 0x38, 0xed, 0xc9, 0x48, 0xed, 0xbb, 0xfa,
	0xfb, 0x8d, 0x07, 0x6e, 0xb8, 0xa3, 0xb6, 0x3e, 0x47, 0x28, 0x7e, 0xb6, 0x96, 0x83, 0xde, 0x3a,
	0xdc, 0x54, 0xf1, 0xa9, 0x34, 0xe9, 0x45, 0x81, 0x48, 0x2c, 0xc6, 0x9f, 0xc9, 0x38, 0x6f, 0x18,
	0x1f, 0x22, 0xd4, 0x3b, 0x0e, 0xd3, 0xe3, 0xb8, 0x7e, 0x21, 0x57, 0x43, 0x98, 0x92, 0x15, 0x98,
	0xcd, 0x25, 0x9d, 0x4c, 0xa5, 0xb2, 0x1f, 0xf9, 0x7d, 0x61, 0xd1, 0xfc, 0x9a, 0x6b, 0xea, 0xeb,
	0x33, 0x88, 0x1d, 0x2f, 0x29, 0xef, 0x34, 0x2c, 0xe0, 0x7f, 0xce, 0xfa, 0x61, 0x26, 0x4c, 0xdb,
	0xc1, 0x91, 0xb6, 0xd3, 0xb8, 0x8c, 0x95, 0xbf, 0x9d, 0x9f, 0xc8, 0x95, 0xf3, 0xa5, 0xc0, 0xf0,
	0x1a, 0x9d, 0x08, 0x44, 0x9a, 0x8a, 0x44, 0xb5, 0xfc, 0x30, 0x1c, 0xb1, 0xc9, 0x13, 0xbd, 0xb0,
	0x34, 0x5e, 0xb8, 0x56, 0xed, 0xc4, 0x4a, 0x41, 0x1e, 0x0d, 0x43, 0x6f, 0x03, 0x6e, 0x1e, 0xd1,
	0x59, 0x07, 0xe7, 0x45, 0x72, 0x2e, 0xec, 0xea, 0x2e, 0x6a, 0xd7, 0x80, 0xff, 0x5f, 0xf6, 0xc3,
	0xc1, 0xf9, 0x2e, 0x39, 0x9b, 0xc4, 0x72, 0x5b, 0xd0, 0x78, 0x3f, 0xcc, 0x9d, 0x15, 0x49, 0x5b,
	0x2a, 0xd1, 0x12, 0x4f, 0x65, 0x7e, 0xe8, 0xa0, 0xbb, 0x44, 0xba, 0x59, 0x02, 0x97, 0x91, 0x43,
	0xd7, 0x61, 0xa8, 0x75, 0xfd, 0x8e, 0x70, 0x50, 0x5c, 0x26, 0xc5, 0x24, 0xae, 0x47, 0xf4, 0x28,
	0x34, 0x02, 0x59, 0xdc, 0x92, 0x03, 0x7e, 0x85, 0xf0, 0x29, 0x66, 0x48, 0x11, 0xcb, 0x38, 0x0b,
	0xfd, 0xd4, 0x65, 0x07, 0xef, 0xb1, 0x82, 0x19, 0x52, 0x8c, 0x51, 0xd6, 0xf7, 0x59, 0xa1, 0x8c,
	0x7a, 0xde, 0x03, 0x53, 0x32, 0x0a, 0xb7, 0x64, 0xe4, 0xb2, 0x89, 0x0f, 0xc8, 0x00, 0x84, 0xa0,
	0xe0, 0x08, 0xd4, 0x5d, 0x1b, 0xf1, 0x21, 0xe1, 0x35, 0xc1, 0x1d, 0xd0, 0xe7, 0x8c, 0x87, 0x8c,
	0x5e, 0xe1, 0xa0, 0xf8, 0x88, 0x14, 0x33, 0x06, 0x46, 0xb7, 0x91, 0x0a, 0x95, 0x06, 0xc2, 0x45,
	0xf2, 0x31, 0xdf, 0x06, 0x21, 0x54, 0xca, 0xb6, 0x88, 0x3a, 0x67, 0xdc, 0x0c, 0x9f, 0x70, 0x29,
	0x99, 0x41, 0x85, 0x9e, 0x3c, 0x7d, 0x3f, 0x51, 0x67, 0xfc, 0xd0, 0xa9, 0x1d, 0x9f, 0x92, 0xa3,
	0x51, 0x42, 0x54, 0x91, 0x2c, 0x1a, 0x47, 0xf3, 0x19, 0x57, 0xc4, 0xc0, 0xe8, 0xe8, 0xa9, 0xd4,
	0x6f, 0x87, 0xa2, 0x35, 0x8e, 0xed, 0x73, 0x3e, 0x7a, 0x05, 0xbb, 0x6a, 0x1a, 0x75, 0xa7, 0x55,
	0xef, 0x69, 0x27, 0xcd, 0x17, 0xdc, 0xe9, 0x1c, 0x40, 0xf8, 0x31, 0xb8, 0x65, 0xe4, 0xa8, 0x77,
	0x90, 0x7d, 0x49, 0xb2, 0xc5, 0x11, 0xe3, 0x9e, 0x46, 0xc2, 0xb8, 0xca, 0xaf, 0x78, 0x24, 0x88,
	0x21, 0x97, 0xae, 0x5a, 0x16, 0x29, 0xbf, 0x3b, 0x5e, 0xd5, 0xbe, 0xe6, 0xaa, 0x15, 0x6c, 0xa5,
	0x6a, 0x0f, 0xc3, 0x22, 0x19, 0xc7, 0xeb, 0xeb, 0x37, 0x3c, 0x58, 0x0b, 0x7a, 0xa3, 0xda, 0xdd,
	0xc7, 0x61, 0x7f, 0x59, 0xce, 0x73, 0xa9, 0x88, 0x14, 0x32, 0x7a, 0xcf, 0xb1, 0x83, 0xf9, 0x2a,
	0x99, 0x79, 0xe2, 0x2f, 0x97, 0x82, 0x55, 0x3f, 0x46, 0xf9, 0xa3, 0xb0, 0x8f, 0xe5, 0x59, 0x94,
	0x88, 0x8e, 0x0c, 0x22, 0xdd, 0xc6, 0x4d, 0x07, 0xf5, 0xb7, 0x43, 0xad, 0xda, 0x30, 0x70, 0x34,
	0x9f, 0x84, 0xbd, 0xe5, 0xef, 0x8d, 0x56, 0xaf, 0x1f, 0xcb, 0x24, 0xb5, 0x18, 0xbf, 0xe3, 0x4e,
	0x95, 0xdc, 0xc9, 0x1c, 0xf3, 0x96, 0x61, 0x26, 0xff, 0xd3, 0xf5, 0x91, 0xfc, 0x9e, 0x44, 0xd3,
	0x03, 0x8a, 0x06, 0x47, 0x47, 0xf6, 0x63, 0x3f, 0x71, 0x99, 0x7f, 0x3f, 0xf0, 0xe0, 0x20, 0x04,
	0x05, 0xf7, 0xc1, 0xde, 0xcd, 0x9e, 0xbe, 0xcb, 0xb4, 0xa5, 0x07, 0xa2, 0xec, 0x3a, 0x58, 0x7e,
	0x2c, 0x67, 0x58, 0xce, 0x9d, 0x42, 0xac, 0x78, 0x8e, 0x67, 0x87, 0x32, 0xbd, 0x79, 0xfb, 0x2e,
	0xd1, 0xaa, 0x50, 0xca, 0x0f, 0x4a, 0xd7, 0x33, 0xdb, 0xe4, 0xaa, 0x46, 0xba, 0xf7, 0x00, 0x16,
	0xba, 0x1a, 0xbc, 0x76, 0xd9, 0xf9, 0xed, 0xb2, 0xd6, 0x95, 0xdc, 0xf5, 0x4e, 0xc0, 0x74, 0x25,
	0x74, 0xed, 0xaa, 0x67, 0x49, 0xd5, 0x30, 0x33, 0xd7, 0xbb, 0x13, 0x26, 0x30, 0x40, 0xed, 0xf8,
	0x73, 0x84, 0xe7, 0xcb, 0xbd, 0xbb, 0xa1, 0xc6, 0xc1, 0x69, 0x47, 0x9f, 0x27, 0xb4, 0x44, 0x10,
	0xe7, 0xd0, 0xb4, 0xe3, 0x2f, 0x30, 0xce, 0x08, 0xe2, 0xee, 0x25, 0xfc, 0xe9, 0xa5, 0x09, 0x1a,
	0x7c, 0x5c, 0xbb, 0x23, 0x30, 0x49, 0x69, 0x69, 0xa7, 0x5f, 0xa4, 0x2f, 0x67, 0xc2, 0xbb, 0x0b,
	0xf6, 0x38, 0x16, 0xfc, 0x65, 0x42, 0x8b, 0xf5, 0x3a, 0x8b, 0xa6, 0x8c, 0x84, 0xb4, 0xe3, 0xaf,
	0x10, 0x6e, 0x52, 0xb8, 0x75, 0x4a, 0x48, 0xbb, 0xe0, 0x55, 0xde, 0x3a, 0x11, 0x58, 0x36, 0x0e,
	0x47, 0x3b, 0xfd, 0x1a, 0x57, 0x9d, 0x11, 0x7d, 0x2e, 0xeb, 0xe5, 0xc0, 0xb3, 0xf3, 0xaf, 0x13,
	0x3f, 0x60, 0xb0, 0x02, 0xc6, 0xc0, 0xb5, 0x2b, 0xde, 0xe0, 0x0a, 0x18, 0x14, 0x1e, 0xa3, 0xe1,
	0x10, 0xb5, 0x9b, 0xde, 0xe4, 0x63, 0x34, 0x94, 0xa1, 0xd8, 0xcd, 0x7c, 0xee, 0xd8, 0x15, 0x6f,
	0x71, 0x37, 0xf3, 0xf5, 0xb8, 0x8d, 0xe1, 0x54, 0xb2, 0x3b, 0xde, 0xe6, 0x6d, 0x0c, 0x85, 0x92,
	0xce, 0xb8, 0xe6, 0xee, 0x44, 0xb2, 0xfb, 0xde, 0x21, 0xdf, 0xdc, 0xae, 0x40, 0xf2, 0x1e, 0x81,
	0xc5, 0xd1, 0x69, 0x64, 0xb7, 0x5e, 0xd8, 0x1e, 0x7a, 0x7f, 0x30, 0xc3, 0x48, 0x87, 0xe7, 0xc2,
	0xa8, 0x24, 0xb2, 0x6b, 0x2f, 0x6e, 0x57, 0x5f, 0x11, 0xcd, 0x20, 0xd2, 0xbf, 0xf5, 0x60, 0x10,
	0x02, 0x76, 0xd7, 0x25, 0x72, 0x19, 0x10, 0x1e, 0x0d, 0xca, 0x00, 0x3b, 0x7f, 0x99, 0x8f, 0x06,
	0x11, 0xde, 0xbd, 0xd0, 0x30, 0x23, 0xc3, 0x6e, 0xb8, 0x52, 0x9e, 0xce, 0x41, 0x62, 0xe8, 0x2d,
	0xd4, 0xa2, 0x2c, 0x0c, 0xf1, 0x11, 0x6b, 0xde, 0x36, 0x22, 0x70, 0x44, 0xb8, 0xc9, 0xfc, 0x1f,
	0x3b, 0x74, 0xbc, 0x18, 0xd0, 0x93, 0x78, 0x8f, 0xe8, 0xb7, 0x75, 0x25, 0x2d, 0xe4, 0x9f, 0x3b,
	0x3c, 0x56, 0x70, 0xb5, 0x3e, 0x95, 0x50, 0xbc, 0xc4, 0xa6, 0x5b, 0xb1, 0xf5, 0x5b, 0xff, 0xda,
	0x29, 0xde, 0x89, 0x0d, 0x64, 0x20, 0xc8, 0xdf, 0x82, 0x2d, 0x82, 0x6b, 0x55, 0x41, 0xfe, 0xe2,
	0x7b, 0x18, 0x26, 0x9f, 0x50, 0x32, 0x4a, 0xfd, 0xc0, 0x46, 0xff, 0x4d, 0x34, 0xaf, 0xc7, 0x82,
	0xf5, 0x65, 0x22, 0xf4, 0xa5, 0xb2, 0xb1, 0xff, 0x10, 0x5b, 0x02, 0x08, 0x77, 0x7c, 0x95, 0xba,
	0xdc, 0xf7, 0xbf, 0x0c, 0x33, 0x80, 0x9b, 0xc6, 0xeb, 0x27, 0xc5, 0x96, 0x8d, 0xfd, 0x8f, 0x37,
	0x4d, 0xeb, 0xf5, 0x18, 0xad, 0xe3, 0x65, 0xfe, 0xfe, 0x6f, 0x83, 0xff, 0x27, 0x78, 0x40, 0x1c,
	0x3b, 0x08, 0xf3, 0xfa, 0xa9, 0x1b, 0xc6, 0x8e, 0xc1, 0x8a, 0x5c, 0x91, 0x6b, 0xf9, 0xe3, 0x7c,
	0x3d, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x6e, 0x63, 0xc0, 0x0e, 0x12, 0x00, 0x00,
}
